-- ============================================================================
-- OiimTech — Supabase Schema + Full Seed Data (SEMUA konten situs)
-- Jalankan di: Supabase Dashboard -> SQL Editor -> New query -> Run
-- Aman dijalankan berulang (idempotent): IF NOT EXISTS + ON CONFLICT DO NOTHING
-- ============================================================================

-- ============================================================================
-- 1. TABEL: orders (pesanan dari formulir booking)
-- ============================================================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_date timestamptz not null default now(),
  service_name text not null,
  price numeric not null default 0,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text not null default '',
  client_id text not null,
  status text not null default 'Pending',
  constraint orders_price_non_negative check (price >= 0),
  constraint orders_status_valid check (
    status in ('Pending', 'Pesanan Diterima', 'Diproses', 'Selesai', 'Dibatalkan')
  )
);

comment on table public.orders is 'Data pesanan layanan dari formulir booking';
comment on column public.orders.client_id is 'Identitas pengunjung (browser localStorage), dipakai filter riwayat';

create index if not exists orders_client_id_idx on public.orders (client_id);
create index if not exists orders_client_ordered_idx on public.orders (client_id, id desc);
create index if not exists orders_order_date_idx on public.orders (order_date desc);

-- update constraint utk tabel yang sudah dibuat dengan versi lama (tanpa 'Pending')
alter table public.orders drop constraint if exists orders_status_valid;
alter table public.orders add constraint orders_status_valid check (
  status in ('Pending', 'Pesanan Diterima', 'Diproses', 'Selesai', 'Dibatalkan')
);
alter table public.orders alter column status set default 'Pending';

-- updated_at untuk orders: tercatat otomatis saat status/baris diubah
-- (mis. admin mengubah status pesanan -> updated_at ikut ter-update)
alter table public.orders
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 2. TABEL: site_content (seluruh konten yang bisa dikelola di panel admin)
--    key      -> services | testimonials | faq | hero | announcement | contacts
--    payload  -> JSONB, bentuknya sama persis dengan data di situs
-- ============================================================================
create table if not exists public.site_content (
  key text primary key
    check (key in ('services', 'testimonials', 'faq', 'hero', 'announcement', 'contacts')),
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

comment on table public.site_content is 'Konten situs yang dikelola via /admin (layanan, testimoni, FAQ, hero, pengumuman, kontak)';

-- Auto-update updated_at setiap kali payload berubah
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_content_set_updated_at on public.site_content;
create trigger site_content_set_updated_at
  before update on public.site_content
  for each row execute function public.set_updated_at();

-- ============================================================================
-- 1b. TABEL: comments (komentar/pertanyaan dari form footer)
-- ============================================================================
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  address text not null default '',
  question text not null,
  created_at timestamptz not null default now()
);

comment on table public.comments is 'Komentar/pertanyaan pengunjung dari form di footer';

create index if not exists comments_created_at_idx on public.comments (created_at desc);

alter table public.comments enable row level security;

drop policy if exists "comments_anon_full" on public.comments;
create policy "comments_anon_full" on public.comments
  for all to anon
  using (true)
  with check (true);

grant select, insert, update, delete on public.comments to anon;

-- ============================================================================
-- 3. ROW LEVEL SECURITY
--    Kunci anon HANYA dipakai di server (Next.js API routes), tidak di browser.
-- ============================================================================
alter table public.orders enable row level security;
alter table public.site_content enable row level security;

drop policy if exists "orders_anon_full" on public.orders;
create policy "orders_anon_full" on public.orders
  for all to anon
  using (true)
  with check (true);

drop policy if exists "site_content_anon_full" on public.site_content;
create policy "site_content_anon_full" on public.site_content
  for all to anon
  using (true)
  with check (true);

-- Hak akses eksplisit untuk role anon (PostgREST) — jaga-jaga bila default diubah
grant usage on schema public to anon;
grant select, insert, update, delete on public.orders to anon;
grant select, insert, update, delete on public.site_content to anon;
grant usage, select on all sequences in schema public to anon;

-- Realtime (opsional): daftarkan orders ke publikasi supabase_realtime
-- agar pesanan baru bisa muncul live di dashboard admin via subscription.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.orders;
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;

-- ============================================================================
-- 4. SEED: SEMUA konten default situs (identik dengan lib/services-data.ts)
--    Hanya diisi bila key-nya belum ada, sehingga konten hasil edit admin
--    di panel tidak akan tertimpa saat script dijalankan ulang.
-- ============================================================================

-- 4.1 Layanan (6 item)
insert into public.site_content (key, payload) values (
  'services',
  $$[
    {"id": 1, "name": "Ganti LCD", "price": 350000, "duration": "2 jam", "warranty": "3 bulan", "icon": "🖥️", "description": "Penggantian layar LCD dengan kualitas original. Mengatasi masalah layar pecah, touchscreen tidak responsif, atau tampilan bergaris."},
    {"id": 2, "name": "Ganti Baterai", "price": 250000, "duration": "1 jam", "warranty": "6 bulan", "icon": "🔋", "description": "Ganti baterai HP Anda yang sudah drop atau kembung. Kami menggunakan baterai berkualitas tinggi untuk daya tahan maksimal."},
    {"id": 3, "name": "Perbaikan Software", "price": 150000, "duration": "1-2 jam", "warranty": "1 bulan", "icon": "📱", "description": "Mengatasi masalah sistem operasi, bootloop, lupa pola/password, atau update software yang gagal."},
    {"id": 4, "name": "Ganti Charging Port", "price": 120000, "duration": "1 jam", "warranty": "3 bulan", "icon": "⚡", "description": "Perbaikan konektor pengisian daya yang longgar atau tidak bisa mengisi daya sama sekali."},
    {"id": 5, "name": "Perbaikan Water Damage", "price": 400000, "duration": "1-2 hari", "warranty": "1 bulan", "icon": "💧", "description": "Penanganan khusus untuk HP yang terkena air. Pembersihan korosi dan penggantian komponen yang rusak akibat cairan."},
    {"id": 6, "name": "Ganti Kamera", "price": 300000, "duration": "1 jam", "warranty": "3 bulan", "icon": "📷", "description": "Perbaikan kamera depan atau belakang yang buram, tidak fokus, atau mati total."}
  ]$$
) on conflict (key) do nothing;

-- 4.2 Testimoni (6 item)
insert into public.site_content (key, payload) values (
  'testimonials',
  $$[
    {"name": "Andi Wijaya", "rating": 5, "comment": "Servis HP cepat dan rapi! Harga transparan. Teknisi sangat profesional dalam menjelaskan kerusakan.", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Andi"},
    {"name": "Sari Dewi", "rating": 5, "comment": "Layarnya diganti, hasilnya seperti baru. Recommended banget buat yang mau servis HP premium!", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Sari"},
    {"name": "Budi Santoso", "rating": 4, "comment": "Ganti baterai cuma 1 jam, langsung bisa dipakai lagi. Garansinya juga cukup lama.", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Budi"},
    {"name": "Lina Marlina", "rating": 5, "comment": "Pelayanan ramah, tempatnya nyaman. HP saya yang kena air bisa hidup lagi!", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Lina"},
    {"name": "Rizky Pratama", "rating": 5, "comment": "Sangat puas dengan hasilnya. Kameranya sekarang jernih banget!", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Rizky"},
    {"name": "Dina Lestari", "rating": 5, "comment": "Prosesnya transparan, bisa ditunggu juga. Top markotop!", "avatar": "https://api.dicebear.com/7.x/adventurer/svg?seed=Dina"}
  ]$$
) on conflict (key) do nothing;

-- 4.3 FAQ (9 item)
insert into public.site_content (key, payload) values (
  'faq',
  $$[
    {"q": "Berapa lama proses perbaikan HP?", "a": "Tergantung jenis kerusakannya. Perbaikan ringan seperti ganti baterai atau charging port selesai dalam 1 jam dan bisa ditunggu. Perbaikan berat seperti water damage atau perbaikan motherboard membutuhkan 1-2 hari kerja."},
    {"q": "Apakah setiap perbaikan mendapatkan garansi?", "a": "Ya. Semua perbaikan di OiimTech bergaransi resmi - mulai 1 bulan untuk perbaikan software hingga 6 bulan untuk penggantian baterai. Garansi berlaku untuk jasa maupun komponen yang kami pasang."},
    {"q": "Apakah ada biaya untuk diagnosa?", "a": "Tidak ada. Diagnosa awal dan konsultasi sepenuhnya gratis. Anda hanya membayar ketika menyetujui estimasi biaya dan perbaikan dilakukan."},
    {"q": "Bagaimana cara memesan layanan?", "a": "Cukup isi formulir di halaman Booking atau klik \"Pesan Sekarang\" pada layanan yang Anda butuhkan. Teknisi kami akan menghubungi Anda lewat WhatsApp dalam 15 menit untuk konfirmasi jadwal."},
    {"q": "Apakah ada layanan antar jemput HP?", "a": "Ada. Kami melayani antar jemput gratis untuk area Surabaya. HP Anda dijemput tim kami, diperbaiki, lalu diantar kembali ke alamat Anda setelah selesai."},
    {"q": "Apakah data di HP saya aman?", "a": "Sangat aman. Kami menerapkan SOP privasi yang ketat - data Anda tidak akan dibuka, disalin, atau disebarluaskan. Sebelum perbaikan, kami sarankan backup data di rumah sebagai langkah pencegahan standar."},
    {"q": "Apakah komponen yang digunakan original?", "a": "Kami menyediakan komponen original dan OEM berkualitas tinggi. Selalu kami informasikan pilihan komponen beserta perbedaan harganya sebelum pengerjaan - keputusan tetap di tangan Anda."},
    {"q": "Merk HP apa saja yang bisa diservis?", "a": "Semua brand kami tangani: Apple, Samsung, Xiaomi, OPPO, VIVO, OnePlus, ASUS, Realme, Infinix, dan lainnya. Termasuk masalah spesifik seperti FaceID Apple, green line Samsung, hingga bootloop Xiaomi."},
    {"q": "Bagaimana metode pembayarannya?", "a": "Pembayaran dilakukan setelah perbaikan selesai dan HP sudah dites menyeluruh. Metodenya fleksibel: tunai, transfer bank, e-wallet (GoPay, OVO, DANA), atau bayar di tempat (COD)."}
  ]$$
) on conflict (key) do nothing;

-- 4.4 Hero section
insert into public.site_content (key, payload) values (
  'hero',
  $${
    "badge": "Buka hari ini - 09.00 - 21.00",
    "titleA": "Service ",
    "titleHighlight": "HP Premium",
    "titleB": " Tanpa Ribet.",
    "subtitle": "LCD pecah, baterai kembung, kena air? Diagnosa gratis, harga transparan, dan garansi resmi - semua dikerjakan teknisi bersertifikat.",
    "stats": [
      {"value": "40+", "label": "HP Diperbaiki"},
      {"value": "4.9/5", "label": "Rating Pelanggan"},
      {"value": "15 mnt", "label": "Respon WhatsApp"}
    ]
  }$$
) on conflict (key) do nothing;

-- 4.5 Pengumuman (banner atas)
insert into public.site_content (key, payload) values (
  'announcement',
  $${
    "enabled": true,
    "text": "Buka setiap hari 09.00 - 21.00 WIB"
  }$$
) on conflict (key) do nothing;

-- 4.6 Kontak & media sosial
insert into public.site_content (key, payload) values (
  'contacts',
  $${
    "whatsapp": "6287817148552",
    "phoneDisplay": "+62 878 1714 8552",
    "email": "info@oiimtech.com",
    "address": "Jl. Dukuh Kupang, Surabaya, Indonesia",
    "instagram": "oiimtech",
    "tiktok": "",
    "hours": "Setiap hari 09.00 - 21.00 WIB"
  }$$
) on conflict (key) do nothing;

-- ============================================================================
-- 5. VERIFIKASI (jalankan terpisah untuk cek hasil)
--    select key, jsonb_array_length(payload) from public.site_content order by key;
-- ============================================================================
